[project]
name = "tp1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "eric891224", email = "s96006730@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "transformers>=5.17.0",
    "trl>=1.13.0",
    "wandb>=0.30.0",
]

[project.scripts]
tp1 = "tp1:main"

[build-system]
requires = ["uv_build>=0.12.14,<0.13.0"]
build-backend = "uv_build"
